[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault_program = "5QYYRm4embEgtbGNc1Rm95BW6dJyJL3VDLhjXSSLQQ15"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/exidz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
